site_name: Center for Computational Research
docs_dir: 'pages'
site_description: 'Center for Computational Research'
site_url: 'https://docs.ccr.buffalo.edu'
copyright: 'Copyright &copy; 2021 Center for Computational Research, University at Buffalo'
repo_name: 'ubccr/ccrdocs'
repo_url: 'https://github.com/ubccr/ccrdocs'
edit_uri: 'blob/main/pages'

theme:
  name: 'readthedocs'
  logo: 'images/logo.png'
  favicon: 'images/favicon.ico'
  include_homepage_in_sidebar: false
  custom_dir: 'theme/'

plugins:
  - search
  - awesome-pages
  - mkdocs-video

markdown_extensions:
  - toc:
      permalink: true
  - footnotes
  - def_list
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - CCR Help: help.md
  - Frequently Asked Questions: faq.md
  - CCR's Public Key Fingerprints: fingerprints.md
  - Accessing CCR Resources:
    - Getting Access: getting-access.md
    - Two Factor Authentication: 2fa.md
    - Getting Started: getting-started.md
    - Available Resources: available-resources.md
  - High Performance Computing:
    - Logging In: hpc/login.md
    - Clusters: hpc/clusters.md
    - Running Jobs: hpc/jobs.md
    - Data Transfer: hpc/data-transfer.md
    - Storage: hpc/storage.md
  - Gateways & Portals:
    - CCR IDM (Identity Management Portal): portals/idm.md
    - ColdFront (Allocations Management Portal): portals/coldfront.md
    - Open OnDemand (Browser based HPC Portal): portals/ood.md
    - UBMoD (Job Metrics Portal): portals/metrics.md
    - WebMO (Chemistry Portal): portals/webmo.md
  - Software:
    - Available Software: software/modules.md
    - Useful Module Commands: software/module-commands.md
    - Building your own software: software/building.md
    - Releases: software/releases.md
  - Cloud:
    - LakeEffect (On-Prem Cloud): cloud/lake-effect.md
    - Using the Cloud: cloud/using.md
    - Advanced Topics: cloud/advanced.md
  - Policies:
    - Accounts & Data Policies: policies/accounts.md
    - Communications Policy: policies/email.md
    - Permitted Use & Misuse of CCR: policies/misuse.md
    - Support, Maintenance, & Installation Policies: policies/support.md
  - How To:  
    - CCR Software Environments: howto/newenv.md  
    - Easybuild: howto/easybuild.md  
    - OnDemand Troubleshooting:  howto/ood-trouble.md  
    - Running Containers: howto/containerization.md   
 
